<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ORIDEServerModule</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="WWDedicatedServer">
      <HintPath>..\..\..\API\Server\WWDedicatedServer.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\OriCoopShared\*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
