<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ORIDEServerModule</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OriCoopDedicatedServer\OriCoopDedicatedServer.Core\OriCoopDedicatedServer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\OriCoopShared\*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
